export * from './auth/login';
export * from './auth/signup';
export * from './dashboard/claims';
export * from './dashboard/claims/file_claim';
export * from './dashboard/id_card/';
export * from './dashboard/payments/';
export * from './dashboard/policy';
export * from './drawer';
export * from './dashboard';
